go get -u -v github.com/Kubuxu/go-os-helper
go get -u -v github.com/bren2010/proquint
go get -u -v github.com/cenkalti/backoff
go get -u -v github.com/dustin/go-humanize
go get -u -v github.com/elgris/jsondiff
go get -u -v github.com/gogo/protobuf/proto
go get -u -v github.com/hashicorp/go-multierror
go get -u -v github.com/hashicorp/golang-lru
go get -u -v github.com/ipfs/dir-index-html
go get -u -v github.com/ipfs/go-bitswap
go get -u -v github.com/ipfs/go-bitswap/decision
go get -u -v github.com/ipfs/go-bitswap/network
go get -u -v github.com/ipfs/go-block-format
go get -u -v github.com/ipfs/go-blockservice
go get -u -v github.com/ipfs/go-cid
go get -u -v github.com/ipfs/go-cidutil
go get -u -v github.com/ipfs/go-cidutil/cidenc
go get -u -v github.com/ipfs/go-datastore
go get -u -v github.com/ipfs/go-datastore/mount
go get -u -v github.com/ipfs/go-datastore/namespace
go get -u -v github.com/ipfs/go-datastore/query
go get -u -v github.com/ipfs/go-datastore/retrystore
go get -u -v github.com/ipfs/go-datastore/sync
go get -u -v github.com/ipfs/go-ds-badger
go get -u -v github.com/ipfs/go-ds-flatfs
go get -u -v github.com/ipfs/go-ds-leveldb
go get -u -v github.com/ipfs/go-ds-measure
go get -u -v github.com/ipfs/go-fs-lock
go get -u -v github.com/ipfs/go-ipfs-blockstore
go get -u -v github.com/ipfs/go-ipfs-chunker
go get -u -v github.com/ipfs/go-ipfs-cmds
go get -u -v github.com/ipfs/go-ipfs-cmds/cli
go get -u -v github.com/ipfs/go-ipfs-cmds/http
go get -u -v github.com/ipfs/go-ipfs-config
go get -u -v github.com/ipfs/go-ipfs-config/serialize
go get -u -v github.com/ipfs/go-ipfs-ds-help
go get -u -v github.com/ipfs/go-ipfs-exchange-interface
go get -u -v github.com/ipfs/go-ipfs-exchange-offline
go get -u -v github.com/ipfs/go-ipfs-files
go get -u -v github.com/ipfs/go-ipfs-posinfo
go get -u -v github.com/ipfs/go-ipfs-routing/none
go get -u -v github.com/ipfs/go-ipfs-routing/offline
go get -u -v github.com/ipfs/go-ipfs-util
go get -u -v github.com/ipfs/go-ipld-cbor
go get -u -v github.com/ipfs/go-ipld-format
go get -u -v github.com/ipfs/go-ipld-git
go get -u -v github.com/ipfs/go-ipns
go get -u -v github.com/ipfs/go-ipns/pb
go get -u -v github.com/ipfs/go-log
go get -u -v github.com/ipfs/go-log/writer
go get -u -v github.com/ipfs/go-merkledag
go get -u -v github.com/ipfs/go-merkledag/test
go get -u -v github.com/ipfs/go-metrics-interface
go get -u -v github.com/ipfs/go-metrics-prometheus
go get -u -v github.com/ipfs/go-mfs
go get -u -v github.com/ipfs/go-path
go get -u -v github.com/ipfs/go-path/resolver
go get -u -v github.com/ipfs/go-unixfs
go get -u -v github.com/ipfs/go-unixfs/file
go get -u -v github.com/ipfs/go-unixfs/importer
go get -u -v github.com/ipfs/go-unixfs/importer/balanced
go get -u -v github.com/ipfs/go-unixfs/importer/helpers
go get -u -v github.com/ipfs/go-unixfs/importer/trickle
go get -u -v github.com/ipfs/go-unixfs/io
go get -u -v github.com/ipfs/go-unixfs/pb
go get -u -v github.com/ipfs/go-verifcid
go get -u -v github.com/ipfs/interface-go-ipfs-core
go get -u -v github.com/ipfs/interface-go-ipfs-core/options
go get -u -v github.com/ipfs/interface-go-ipfs-core/options/namesys
go get -u -v github.com/ipfs/interface-go-ipfs-core/path
go get -u -v github.com/jbenet/go-is-domain
go get -u -v github.com/jbenet/go-temp-err-catcher
go get -u -v github.com/jbenet/goprocess
go get -u -v github.com/jbenet/goprocess/context
go get -u -v github.com/jbenet/goprocess/periodic
go get -u -v github.com/libp2p/go-libp2p
go get -u -v github.com/libp2p/go-libp2p-autonat-svc
go get -u -v github.com/libp2p/go-libp2p-circuit
go get -u -v github.com/libp2p/go-libp2p-connmgr
go get -u -v github.com/libp2p/go-libp2p-core/connmgr
go get -u -v github.com/libp2p/go-libp2p-core/crypto
go get -u -v github.com/libp2p/go-libp2p-core/host
go get -u -v github.com/libp2p/go-libp2p-core/metrics
go get -u -v github.com/libp2p/go-libp2p-core/mux
go get -u -v github.com/libp2p/go-libp2p-core/network
go get -u -v github.com/libp2p/go-libp2p-core/peer
go get -u -v github.com/libp2p/go-libp2p-core/peerstore
go get -u -v github.com/libp2p/go-libp2p-core/protocol
go get -u -v github.com/libp2p/go-libp2p-core/routing
go get -u -v github.com/libp2p/go-libp2p-http
go get -u -v github.com/libp2p/go-libp2p-kad-dht
go get -u -v github.com/libp2p/go-libp2p-kad-dht/opts
go get -u -v github.com/libp2p/go-libp2p-kbucket
go get -u -v github.com/libp2p/go-libp2p-loggables
go get -u -v github.com/libp2p/go-libp2p-mplex
go get -u -v github.com/libp2p/go-libp2p-peerstore/pstoremem
go get -u -v github.com/libp2p/go-libp2p-pnet
go get -u -v github.com/libp2p/go-libp2p-pubsub
go get -u -v github.com/libp2p/go-libp2p-pubsub-router
go get -u -v github.com/libp2p/go-libp2p-quic-transport
go get -u -v github.com/libp2p/go-libp2p-record
go get -u -v github.com/libp2p/go-libp2p-routing-helpers
go get -u -v github.com/libp2p/go-libp2p-secio
go get -u -v github.com/libp2p/go-libp2p-swarm
go get -u -v github.com/libp2p/go-libp2p-tls
go get -u -v github.com/libp2p/go-libp2p-yamux
go get -u -v github.com/libp2p/go-libp2p/p2p/discovery
go get -u -v github.com/libp2p/go-libp2p/p2p/host/basic
go get -u -v github.com/libp2p/go-libp2p/p2p/host/routed
go get -u -v github.com/libp2p/go-libp2p/p2p/protocol/identify
go get -u -v github.com/libp2p/go-libp2p/p2p/protocol/ping
go get -u -v github.com/libp2p/go-maddr-filter
go get -u -v github.com/mr-tron/base58/base58
go get -u -v github.com/multiformats/go-multiaddr
go get -u -v github.com/multiformats/go-multiaddr-dns
go get -u -v github.com/multiformats/go-multiaddr-net
go get -u -v github.com/multiformats/go-multibase
go get -u -v github.com/multiformats/go-multihash
go get -u -v github.com/opentracing/opentracing-go
go get -u -v github.com/pkg/errors
go get -u -v github.com/prometheus/client_golang/prometheus
go get -u -v github.com/prometheus/client_golang/prometheus/promhttp
go get -u -v github.com/syndtr/goleveldb/leveldb/opt
go get -u -v github.com/whyrusleeping/base32
go get -u -v github.com/whyrusleeping/go-sysinfo
go get -u -v github.com/whyrusleeping/multiaddr-filter
go get -u -v github.com/whyrusleeping/tar-utils
go get -u -v go.uber.org/fx
go get -u -v gopkg.in/cheggaaa/pb.v1
